### ISSUE TITLE
RSS feed for getting FOOD

### ISSUE THREAD

**Issue by verschoof** [SweetLakePHP/SweetLakePHP#43]
Maybe its nice to connect a agenda to a RSS feed.
This feed will give you a reminder like:

```
Hey, 

You need you to get some hotdogs!
What we need:
- Zuurkool
- 30 Broodjes (puntjes)
- 5 Blikken Knaks
```

Display message at 8:00
Reminder at 15:00

**Comment by dennisdegreef** [comment]
Issue can be closed in favor of #82 ?
